### ISSUE TITLE
Research and create a scouting application (use school iPads?)

### ISSUE THREAD

**Issue by josephtcoyle** [FRC-6217/Team2019#11]
Lead by Preston
Helped by Zoe, Spencer, Ben, Ryan

**Comment by stcoyle137** [comment]
https://www.team2052.com/frckrawler/
This is one app I found

**Comment by stcoyle137** [comment]
Another option is to create an app using this base format that will work for chromebooks
https://support.google.com/chrome/a/answer/2714278?hl=en
I have tested a little using this but would take a lot of work to get a complete scouting app.

**Comment by stcoyle137** [comment]
One more option 
https://play.google.com/store/apps/details?id=org.growingstems.scouting&hl=en
