### ISSUE TITLE
Design/build battery case with multiport charger

### ISSUE THREAD

**Issue by josephtcoyle** [FRC-6217/Team2019#18]
Check Chief Delphi for ideas on battery systems.
Check AndyMark for a multiport charger.

**Comment by NickEngebretsen** [comment]
https://www.andymark.com/products/battery-charger-3-bank-6-amp-dual-pro-rs3-with-sb-50a-connectors

This should work fine. Other third party chargers offer temp readings but have different battery-to-charger connecting assemblies. Using just one charger allows for us to use one less charging port at the tournament
