### ISSUE TITLE
Software training on Github and using branches for development.

### ISSUE THREAD

**Issue by josephtcoyle** [FRC-6217/Team2019#19]
1. Always assign 2 or more people to a task, allow them to learn together, help each other to learn, and check each other's work.

2. Create a "coding standard" with ways to organize code - file names, variable names, ect. - to make code easier to read and change.

3. Use a Github branching model instead of having everyone committing to one branch that can sometimes be WIP and not be able to be used on the robot. (Model I was thinking about - https://nvie.com/posts/a-successful-git-branching-model/)

**Comment by stcoyle137** [comment]
For the code standard, there is a Eclipse plugin called checkstyle that check the code so the style of variables, methods, and class names are the same for the whole project. The download is [here](https://checkstyle.org/eclipse-cs/#!/) and the website is [here](http://checkstyle.sourceforge.net/). Another thing that we can use is not an auto checker but is the Oracle suggested style of code and the documentation of the style is [here](https://www.oracle.com/technetwork/java/javase/documentation/codeconvtoc-136057.html) but it was last updated in 1999.
