### ISSUE TITLE
Seasons Lessons and Thoughts for Next Year

### ISSUE THREAD

**Issue by josephtcoyle** [FRC-6217/Team2019#49]
Jack
2020 ideas to consider
•	Clipboard of the game field - on a whiteboard, erasable 
•	Bomb hat for MC 
•	PDP abilities/software - amp usage
•	Students trained on Plasma Cutter & Mill (as well as Mentors)
•	Review last 5 years of games to see similarities - Evaluate what platform worked the best. 
•	Is there a skill set that we could benefit from prototyping whys to accomplish the skill
•	Build a base robot with the same frame & drive train, so drive team can practice driving will the build team & design team are working on the competition robot
•	Investigate other drive systems for arms or functions, to include tube belt or steel belts.
•	Wire diagram/schematic
Just an observation, it seemed as if the drive team was smoother with robot operation when the power was limited.
Dave
- clean up the closets. 
- let the software team finish this years robot. 
- review final budget. 
- collect and save power and other data from roborio from Iowa. We should understand the data and come up with better power management. 
Brent
My thoughts on off season events:
1. Practice for new drivers.
2. Let's finish the robot by getting the auto drive working. Can only help for next year.
3. Helps get new student leadership into the grove.
4. Gives a reason to work out swerve drive power problems. Also gyro problems.
5. Maybe get the LIDAR on and working. (If we have the budget to get it now).

**Comment by stcoyle137** [comment]
> Bomb hat for MC

Bread Hat^
